//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `CoffeMach.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package servicios;

/** @hidden */
public class _LogisticServicePrxI extends com.zeroc.Ice._ObjectPrxI implements LogisticServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
